//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Models
{
    using CorePersistence.Repository;
    using System;
    
    public partial class UserAccounts:Entity
    {
        public string UserId { get; set; }
        public string AccountTitle { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string AccountUrl { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
