//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Models
{
    using CorePersistence.Repository;
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotes:Entity
    {
        public string UserId { get; set; }
        public string NoteTitle { get; set; }
        public string NoteText { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
